import { container } from "tsyringe";
import { Router } from "express";
import { TrainerPackageController } from "../controllers/TrainerPackageController.js";
import { authMiddleware } from "../middlewares/authMiddleware.js";
import { roleMiddleware } from "../middlewares/roleMiddleWare.js";
import { validate } from "../middlewares/validate.js";
import { createPackageSchema } from "../validators/trainerPackage.validator.js";
const trainerPackageController=container.resolve(TrainerPackageController);
const router=Router();
router.post("/",authMiddleware,roleMiddleware("trainer"),validate(createPackageSchema),trainerPackageController.createPackage);
router.put("/:packageId",authMiddleware,roleMiddleware("trainer"),trainerPackageController.updatePackage);
router.delete("/:packageId",authMiddleware,roleMiddleware("trainer"),trainerPackageController.deletePackage);
router.get("/trainer/:trainerId",trainerPackageController.getActivePackages);
router.get("/:packageId",trainerPackageController.getPackageById);
export default router;