import express from "express";
import { container } from "tsyringe";
import { TrainerOnboardingController } from "../controllers/TrainerOnboardingController.js";
import { trainerAuthMiddleware } from "../middlewares/trainerAuthMiddleware.js";
import { validate } from "../middlewares/validate.js";
import { updateTrainerCertificationSchema, updateTrainerPackageSchema, updateTrainerProfileSchema } from "../validators/traineronboarding.validator.js";
import { upload } from "../middlewares/upload.js";
const router=express.Router();
const controller=container.resolve(TrainerOnboardingController);
router.get("/status",trainerAuthMiddleware,controller.getTrainerOnboardingStatus.bind(controller));
router.put("/profile",trainerAuthMiddleware,validate(updateTrainerProfileSchema),controller.updateTrainerProfile.bind(controller));
router.put("/certifications",trainerAuthMiddleware,validate(updateTrainerCertificationSchema),controller.updateTrainerCertifications.bind(controller));
router.put("/packages",trainerAuthMiddleware,validate(updateTrainerPackageSchema),controller.updateTrainerPackages.bind(controller));
router.put("/complete",trainerAuthMiddleware,controller.completeTrainerOnboarding.bind(controller));
router.post("/avatar",trainerAuthMiddleware,upload.single("avatar"),controller.uploadAvatar);
router.post("/documents",trainerAuthMiddleware,upload.array("documents", 5),controller.uploadDocuments);
export default router;