import express from "express";
import { container } from "tsyringe";
import { TrainerOnboardingController } from "../controllers/TrainerOnboardingController.ts";
import { authMiddleware } from "../middlewares/authMiddleware.ts";
import { roleMiddleware } from "../middlewares/roleMiddleWare.ts";
import { validate } from "../middlewares/validate.ts";
import { updateTrainerCertificationSchema, updateTrainerPackageSchema, updateTrainerProfileSchema } from "../validators/traineronboarding.validator.ts";
import { upload } from "../middlewares/upload.ts";
const router=express.Router();
const controller=container.resolve(TrainerOnboardingController);
router.get("/status",authMiddleware,roleMiddleware("trainer"),controller.getTrainerOnboardingStatus.bind(controller));
router.put("/profile",authMiddleware,roleMiddleware("trainer"),validate(updateTrainerProfileSchema),controller.updateTrainerProfile.bind(controller));
router.put("/certifications",authMiddleware,roleMiddleware("trainer"),validate(updateTrainerCertificationSchema),controller.updateTrainerCertifications.bind(controller));
router.put("/packages",authMiddleware,roleMiddleware("trainer"),validate(updateTrainerPackageSchema),controller.updateTrainerPackages.bind(controller));
router.put("/complete",authMiddleware,roleMiddleware("trainer"),controller.completeTrainerOnboarding.bind(controller));
router.post("/avatar",authMiddleware,roleMiddleware("trainer"),upload.single("avatar"),controller.uploadAvatar);
router.post("/documents",authMiddleware,roleMiddleware("trainer"),upload.array("documents", 5),controller.uploadDocuments);
export default router;