export enum PlanStatus {
  DRAFT = "DRAFT",
  ACTIVE = "ACTIVE",
  ARCHIVED = "ARCHIVED",
}

export enum Goal {
  WEIGHT_LOSS = "WEIGHT_LOSS",
  MUSCLE_GAIN = "MUSCLE_GAIN",
  ENDURANCE = "ENDURANCE",
  GENERAL_FITNESS = "GENERAL_FITNESS",
}

export enum FitnessLevel {
  BEGINNER = "BEGINNER",
  INTERMEDIATE = "INTERMEDIATE",
  ADVANCED = "ADVANCED",
}

export enum DietPreference {
  NO_RESTRICTION = "NO_RESTRICTION",
  VEGETARIAN = "VEGETARIAN",
  VEGAN = "VEGAN",
  KETO = "KETO",
  PALEO = "PALEO",
}

export enum WorkoutType {
  PUSH = "PUSH",
  PULL = "PULL",
  LEGS = "LEGS",
  UPPER_BODY = "UPPER_BODY",
  LOWER_BODY = "LOWER_BODY",
  FULL_BODY = "FULL_BODY",
  CARDIO = "CARDIO",
  HIIT = "HIIT",
  CORE = "CORE",
  YOGA = "YOGA",
  REST = "REST",
}

export enum MealType {
  BREAKFAST = "BREAKFAST",
  MORNING_SNACK = "MORNING_SNACK",
  LUNCH = "LUNCH",
  EVENING_SNACK = "EVENING_SNACK",
  DINNER = "DINNER",
}

export enum WeekDay {
  MONDAY = "MONDAY",
  TUESDAY = "TUESDAY",
  WEDNESDAY = "WEDNESDAY",
  THURSDAY = "THURSDAY",
  FRIDAY = "FRIDAY",
  SATURDAY = "SATURDAY",
  SUNDAY = "SUNDAY",
}